#! /bin/csh -f

#  Creates .afm files from the STIX .otf fonts
#  
#  Usage:  ./makeAFM

foreach file (~/Library/Fonts/STIX*.*tf)
  echo ""
  echo $file:t
  fontforge -lang=ff -c 'Open("'$file'");Generate("afm/'$file:t:r'.afm")'
end
