#! /bin/csh -f

#  Put the font files into the proper locations
#  
#  Usage: ./makeInstall

#
#  Copy the font files into the system font directory
#
#rm ~/Library/Fonts/MathJax_*
cp otf/*.otf ~/Library/Fonts
cp ttf/*Greek*.ttf ~/Library/Fonts

#
#  Put the fonts into the MathJax fonts folder
#  
rm ../../../../mathjax/fonts/HTML-CSS/TeX/otf/*.*
rm ../../../../mathjax/fonts/HTML-CSS/TeX/eot/*.*
rm ../../../../mathjax/fonts/HTML-CSS/TeX/svg/*.*
cp otf/*.otf ../../../../mathjax/fonts/HTML-CSS/TeX/otf
cp eot/*.eot ../../../../mathjax/fonts/HTML-CSS/TeX/eot
cp svg/*.svg ../../../../mathjax/fonts/HTML-CSS/TeX/svg

