#! /bin/tcsh -f

#  Makes the complete set of TeX image fonts
#  and installs them in the proper location.

echo "====================================="
echo "PNG Suite:"
./makePNGsuite
echo "====================================="
echo "Range Suite:"
./makeRangeSuite
echo "====================================="
echo "Data:"
./makeData
echo "====================================="
echo "Install:"
./makeInstall
echo "====================================="
