#! /bin/tcsh -f

#  Makes the data files needed by the HTML-CSS output jax
#  for ALL the MathJax image fonts

./makeRanges MathJax_AMS-Regular
./makeRanges MathJax_Caligraphic-Bold
./makeRanges MathJax_Caligraphic-Regular
./makeRanges MathJax_Main-Bold
./makeRanges MathJax_Main-Italic
./makeRanges MathJax_Main-Regular
./makeRanges MathJax_Math-BoldItalic
./makeRanges MathJax_Math-Italic
./makeRanges MathJax_Size1-Regular
./makeRanges MathJax_Size2-Regular
./makeRanges MathJax_Size3-Regular
./makeRanges MathJax_Size4-Regular
./makeRanges MathJax_Fraktur-Regular
./makeRanges MathJax_Fraktur-Bold
./makeRanges MathJax_SansSerif-Regular
./makeRanges MathJax_SansSerif-Bold
./makeRanges MathJax_SansSerif-Italic
./makeRanges MathJax_Script-Regular
./makeRanges MathJax_Typewriter-Regular

#./makeRanges MathJax_Greek-Bold
#./makeRanges MathJax_Greek-BoldItalic
#./makeRanges MathJax_Greek-Italic
#./makeRanges MathJax_Greek-Regular

